use_frameworks!

target 'XYFSummerLib_Example' do
  pod 'XYFSummerLib', :path => '../'

  target 'XYFSummerLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
